name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login 4453acr.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t 4453acr.azurecr.io/app:latest .
        docker push 4453acr.azurecr.io/app:latest
